name = "banking-api"
compatibility_date = "2023-12-01"

[vars]
SUPABASE_PROJECT_URL="https://dxqjcnrnwioywjynhdtt.supabase.co"
SUPABASE_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cWpjbnJud2lveXdqeW5oZHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg3MTk0MjYsImV4cCI6MjAyNDI5NTQyNn0.treloc6dEbhhd15ILlcm0-qFpHPWzfXhP2BkMlwZv3c"
SUPABASE_DATABASE_PASSWORD="LG37Jyr2gemVMDtq"
BELVO_SECRET_KEY_ID="37bab290-9498-4ac6-b6f1-431b05261590"
BELVO_SECRET_PASSWORD="y7_yeOU##yF@IhVxZrMpZRQBjdXbUSapKPT_Wpo8kcDmoOE9u4oK4eiHUP#qmsyS"
BELVO_BASE_URL="https://sandbox.belvo.com"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
